# Generated by Django 5.0.7 on 2024-07-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_app', '0002_medicine_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
