# Generated by Django 5.0.7 on 2024-07-13 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_app', '0003_alter_medicine_expiry_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
