# Generated by Django 5.0.7 on 2024-07-15 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_app', '0005_remove_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='medicine',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
