# Generated by Django 5.0.7 on 2024-07-16 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_app', '0007_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='medicine',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
