# Generated by Django 5.0.7 on 2024-07-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_app', '0011_alter_customer_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacist',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='pharmacist',
            name='last_name',
        ),
        migrations.AddField(
            model_name='manager',
            name='password',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
