# Generated by Django 5.0.7 on 2024-07-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_app', '0012_remove_pharmacist_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='expiry_date',
            field=models.DateField(default='2024-05-07'),
        ),
    ]
